spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  h2:
    console:
      enabled: true