spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always


# actuator : 웹에 모든 엔드포인트 노출.
management:
  endpoints:
    web:
      exposure:
        include: "*"

#server:
#  ssl:
#    key-store-type: PKCS12 # 타입 지정
#    key-store: classpath:keystore/sbip.p12 # 인증서 포함한 파일 위치
#    key-store-password: p@ssw0rd # 비밀번호
#    key-alias: sbip # 매핑할 별명
#  port: 8443 # HTTPS 포트 설정

logging:
  level:
    org:
      springframework:
        security: DEBUG

# catalina.session.StandardManager :  Exception loading sessions from persistent storage 에러 해결
# 웹어플리케이션의 세션과 톰캣의 세션이 기대하는 세션과 달라서 발생. Tomcat의 SESSIONS.ser 파일이 손상되었거나 예상하지 못한 데이터로 채워졌을 때 이 오류가 발생
# Tomcat의 세션 지속성을 끄면, 애플리케이션 재시작 또는 서버 재시작시에 세션 상태가 유지되지 않음
server:
  servlet:
    session:
      persistent: false


